### ISSUE TITLE
Permission denied on windows11

### ISSUE THREAD

**Issue by RainyBow** [richardpenman/browsercookie#19]
With Win11 Admin terminal  powershell 
```
PS C:\Users\xxxx\PycharmProjects\xxxx> python main.py
Traceback (most recent call last):
  File "C:\Users\xxxx\PycharmProjects\xxxx\main.py", line 19, in <module>
    chrome_cookie = browsercookie.chrome()
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\browsercookie\__init__.py", line 540, in chrome
    return Chrome(cookie_files).load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\browsercookie\__init__.py", line 99, in load
    for cookie in sorted(self.get_cookies(), key=lambda cookie: cookie.expires):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\browsercookie\__init__.py", line 156, in get_cookies
    with create_local_copy(cookie_file) as tmp_cookie_file:
  File "C:\Python311\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\browsercookie\__init__.py", line 74, in create_local_copy
    with open(cookie_path, 'rb') as cookie_file:
         ^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\xxxx\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Network\\Cookies'
```

**Comment by RainyBow** [comment]
It works fine after closed chrome browser!!!

**Comment by fpemud** [comment]
Is there any way to get this working without closing Chrome?
I think this restriction is a pain point of inconvenience.
