### ISSUE TITLE
Errors initializing plugin EntryPoints

### ISSUE THREAD

**Issue by dubiousjim** [richardpenman/browsercookie#3]
I installed browsercookie (in the user location) using pip-3.6. Using MacPorts on Mac OS 10.15.6 if that matters.

When I `import browsercookie` inside a python 3.6.12 session, I get this error:

```
Error initializing plugin EntryPoint(name='kwallet', value='keyring.backends.kwallet', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/importlib_metadata/api.py", line 67, in load
    attrs = filter(None, match.group('attr').split('.'))
AttributeError: 'NoneType' object has no attribute 'split'
Error initializing plugin EntryPoint(name='secretservice', value='keyring.backends.SecretService', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/importlib_metadata/api.py", line 67, in load
    attrs = filter(None, match.group('attr').split('.'))
AttributeError: 'NoneType' object has no attribute 'split'
Error initializing plugin EntryPoint(name='windows', value='keyring.backends.Windows', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/importlib_metadata/api.py", line 67, in load
    attrs = filter(None, match.group('attr').split('.'))
AttributeError: 'NoneType' object has no attribute 'split'
Error initializing plugin EntryPoint(name='chainer', value='keyring.backends.chainer', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/importlib_metadata/api.py", line 67, in load
    attrs = filter(None, match.group('attr').split('.'))
AttributeError: 'NoneType' object has no attribute 'split'
Error initializing plugin EntryPoint(name='macos', value='keyring.backends.OS_X', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/importlib_metadata/api.py", line 67, in load
    attrs = filter(None, match.group('attr').split('.'))
AttributeError: 'NoneType' object has no attribute 'split'
Error initializing plugin EntryPoint(name='gnome', value='keyrings.alt.Gnome', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/importlib_metadata/api.py", line 67, in load
    attrs = filter(None, match.group('attr').split('.'))
AttributeError: 'NoneType' object has no attribute 'split'
Error initializing plugin EntryPoint(name='google', value='keyrings.alt.Google', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/importlib_metadata/api.py", line 67, in load
    attrs = filter(None, match.group('attr').split('.'))
AttributeError: 'NoneType' object has no attribute 'split'
Error initializing plugin EntryPoint(name='windows (alt)', value='keyrings.alt.Windows', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/importlib_metadata/api.py", line 67, in load
    attrs = filter(None, match.group('attr').split('.'))
AttributeError: 'NoneType' object has no attribute 'split'
Error initializing plugin EntryPoint(name='file', value='keyrings.alt.file', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/importlib_metadata/api.py", line 67, in load
    attrs = filter(None, match.group('attr').split('.'))
AttributeError: 'NoneType' object has no attribute 'split'
Error initializing plugin EntryPoint(name='keyczar', value='keyrings.alt.keyczar', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/importlib_metadata/api.py", line 67, in load
    attrs = filter(None, match.group('attr').split('.'))
AttributeError: 'NoneType' object has no attribute 'split'
Error initializing plugin EntryPoint(name='multi', value='keyrings.alt.multi', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/importlib_metadata/api.py", line 67, in load
    attrs = filter(None, match.group('attr').split('.'))
AttributeError: 'NoneType' object has no attribute 'split'
Error initializing plugin EntryPoint(name='pyfs', value='keyrings.alt.pyfs', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/importlib_metadata/api.py", line 67, in load
    attrs = filter(None, match.group('attr').split('.'))
AttributeError: 'NoneType' object has no attribute 'split'
```

However, the module then seems to work. Any advice?

**Comment by dubiousjim** [comment]
Seems like this is an error with the `keyring` metadata, not `browsercookie`. Reported [as an issue over there](https://github.com/jaraco/keyring/issues/470).
