### ISSUE TITLE
what's the matter?

### ISSUE THREAD

**Issue by OnlyStudyCanMakeMeHappy** [richardpenman/browsercookie#4]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\cjxhs\Anaconda3\lib\site-packages\browsercookie\__init__.py", line 397, in chrome
    return Chrome(cookie_file).load()
  File "C:\Users\cjxhs\Anaconda3\lib\site-packages\browsercookie\__init__.py", line 87, in load
    for cookie in self.get_cookies():
  File "C:\Users\cjxhs\Anaconda3\lib\site-packages\browsercookie\__init__.py", line 149, in get_cookies
    value = self._decrypt(item[5], item[6], key=key)
  File "C:\Users\cjxhs\Anaconda3\lib\site-packages\browsercookie\__init__.py", line 183, in _decrypt
    return win32crypt.CryptUnprotectData(encrypted_value, None, None, None, 0)[1].decode("utf-8")
pywintypes.error: (87, 'CryptProtectData', 'The data is invalid')

**Comment by moneyblind** [comment]
There is a branch that fixes this; Issue is with a change in the encryption with chrome 80+.

**Comment by OnlyStudyCanMakeMeHappy** [comment]
> There is a branch that fixes this; Issue is with a change in the encryption with chrome
Is borisbabic/browser_cookie3?

**Comment by moneyblind** [comment]
That one claims to fix the issue, but I have not tested it. I grabbed another fork. I honestly am probably going to test that one as it is a little more active. You cannot go wrong with testing
